version: "3.7"

services:
  app:
    image: node:16.13.1-alpine3.13
    command: sh -c "yarn install && yarn dev"
    ports:
      - 3001:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      REACT_APP_HOST: http://localhost:3000/api
      REACT_APP_HOST_CHAT: http://localhost:3004
      REACT_NAME: react
