version: "3.7"

services:
  app:
    image: node:16.13.1-alpine3.13
    command: sh -c "yarn install && yarn dev"
    ports:
      - 3003:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
        NEXT_PUBLIC_HOST: http://localhost:3000
        NEXT_PUBLIC_URL: http://localhost:3001
        NEXT_PUBLIC_URL_SHIPPING: https://online-gateway.ghn.vn/shiip/public-api
        NEXT_PUBLIC_TOKEN_SHIPPING: 12902e79-457d-11ed-ad26-3a4226f77ff0
        NEXT_PUBLIC_SHOP_ID_SHIPPING: 3324284
        NEXT_PUBLIC_FORM_DISTRICT_SHIPPING: 3695
